services:
  postgres:
    image: postgres:16
    container_name: devforge-db
    environment:
      POSTGRES_DB: devforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - devforge_data:/var/lib/postgresql/data

volumes:
  devforge_data: